### ISSUE TITLE
Undefined class constant

### ISSUE THREAD

**Issue by PhpNet** [thepinecode/blade-filters#3]
Hello!

L5.8
php 7.3.0
 

Undefined class constant 'ucfirst' (View: /var/www/.../resources/views/welcome.blade.php)

Contents of welcome.blade:

`{{'foo' | ucfirst}}`

**Comment by iamgergo** [comment]
Hi!

The only way I could reproduce this issue is not having the package.

Also, – it's just a thought – try it without any space, because in some cases, the editors put different "spaces" between {{ }} characters. Maybe that's the issue.

**Comment by SeanJA** [comment]
I just tried with various goofy amounts of spacing and it seems to work fine?

**Comment by iamgergo** [comment]
I close this due to inactivity.

**Comment by indapublic** [comment]
Same error

```
laravel/framework                     v5.6.39            The Laravel Framework.
thepinecode/blade-filters             v0.3.2             Use filters easily in your blade templates.
```

Tried with many variants of spaces, tried cache clearing. Nothing helps.

Compiled php looks like:

```
<?php echo e($somestring|slug); ?>
```

**Comment by iamgergo** [comment]
@indapublic Can you send what do you have in your blade template?

Thanks.

**Comment by indapublic** [comment]
@iamgergo Thanks for reply. Will send in Monday

**Comment by indapublic** [comment]
@iamgergo Missed limitations section. Raw echo type was used. Works with regular
