### ISSUE TITLE
Bug when using 2 filters on the same line

### ISSUE THREAD

**Issue by AdrienPoupa** [thepinecode/blade-filters#4]
Hi,

I tried to compile the following line:

` {{ $cash_acct->value | money }} growing at {{ $cash_acct->growth_rate | percentage }}`

it compiles to:

`<?php echo e(\Pine\BladeFilters\BladeFilters::percentage(\Pine\BladeFilters\BladeFilters::money); ?> growing at <?php echo e($cash_acct->growth_rate($cash_acct->value))); ?>`

so it mixes up the filters

Now if I do:

```
{{ $cash_acct->value | money }} growing at
{{ $cash_acct->growth_rate | percentage }}
```

then I get the correct:

```
 <?php echo e(\Pine\BladeFilters\BladeFilters::money($cash_acct->value)); ?> growing at
                            <?php echo e(\Pine\BladeFilters\BladeFilters::percentage($cash_acct->growth_rate)); ?>
```

This is preventing me from using the package.

**Comment by iamgergo** [comment]
@AdrienPoupa Hi,

Thanks for your feedback. You are right, this was a bug, that the package caused.
Now, I set the regexp to non-greedy, so it should work well even if it's one or multiple lines as well.

I pushed a new release, so you may update your packages via composer to pull in the latest code.
After that, I think you need to recompile the views, but they should be good now.

Please let me know if it works for you as well!

Thanks!

**Comment by AdrienPoupa** [comment]
Great thank you!
