### ISSUE TITLE
Bug when wrap with html tags

### ISSUE THREAD

**Issue by liyu001989** [thepinecode/blade-filters#6]
this cause error
```
<h1> {{ 'this is a title' | title }} </h1>
```

![image](https://user-images.githubusercontent.com/2981799/59149232-8dece580-8a45-11e9-882f-5f6e1b6891a7.png)

this is right
```
<h1> {{ 'this is a title' | title }}
 </h1>
```

because this regular  

```
        return preg_replace_callback('/(?<={{)(.*?)(?=}}+$)/mu', function ($matches) {
            return $this->parseFilters($matches[0]);
        }, $value);
```

maybe should not use  `$`

**Comment by iamgergo** [comment]
@liyu001989 Hey!

Thanks, I take a look and try to fix it! I'll let you know soon!

Thanks!

**Comment by iamgergo** [comment]
@liyu001989 I updated the regex. It should work well now.

Please update your package to get the new release.

Thanks a lot!

**Comment by liyu001989** [comment]
nice,  it works 👍
